import '@testing-library/jest-dom/vitest';
import { act, fireEvent, render, screen } from '@testing-library/react';
import { describe, expect, it, vi } from 'vitest';
import { ChatWorkspacePicker } from './chat.workspace-picker.js';

const noop = async (): Promise<null> => null;

describe('ChatWorkspacePicker', () => {
  it('renders the current workspace path on the trigger', () => {
    render(
      <ChatWorkspacePicker
        value="/tmp/my-workspace"
        onChange={vi.fn()}
        onBrowse={noop}
        onOpen={vi.fn()}
      />,
    );
    expect(screen.getByTestId('chat-workspace-picker-trigger').textContent).toContain(
      '/tmp/my-workspace',
    );
  });

  it('shows a "Set directory…" hint when no workspace is set', () => {
    render(
      <ChatWorkspacePicker value={undefined} onChange={vi.fn()} onBrowse={noop} onOpen={vi.fn()} />,
    );
    expect(screen.getByTestId('chat-workspace-picker-trigger').textContent).toContain(
      'Set directory…',
    );
  });

  it('is closed by default', () => {
    render(
      <ChatWorkspacePicker value="/tmp/ws" onChange={vi.fn()} onBrowse={noop} onOpen={vi.fn()} />,
    );
    expect(screen.queryByTestId('chat-workspace-picker-menu')).not.toBeInTheDocument();
  });

  it('opens the menu on trigger click', () => {
    render(
      <ChatWorkspacePicker value="/tmp/ws" onChange={vi.fn()} onBrowse={noop} onOpen={vi.fn()} />,
    );
    fireEvent.click(screen.getByTestId('chat-workspace-picker-trigger'));
    expect(screen.getByTestId('chat-workspace-picker-menu')).toBeInTheDocument();
  });

  it('does not open when disabled', () => {
    render(
      <ChatWorkspacePicker
        value="/tmp/ws"
        onChange={vi.fn()}
        onBrowse={noop}
        onOpen={vi.fn()}
        disabled
      />,
    );
    fireEvent.click(screen.getByTestId('chat-workspace-picker-trigger'));
    expect(screen.queryByTestId('chat-workspace-picker-menu')).not.toBeInTheDocument();
  });

  it('commits the chosen directory from the folder picker', async () => {
    const onChange = vi.fn().mockResolvedValue(undefined);
    const onBrowse = vi.fn().mockResolvedValue('/tmp/new-dir');
    render(
      <ChatWorkspacePicker
        value="/tmp/ws"
        onChange={onChange}
        onBrowse={onBrowse}
        onOpen={vi.fn()}
      />,
    );
    fireEvent.click(screen.getByTestId('chat-workspace-picker-trigger'));
    await act(async () => {
      fireEvent.click(screen.getByTestId('chat-workspace-picker-browse'));
    });
    expect(onBrowse).toHaveBeenCalledTimes(1);
    expect(onChange).toHaveBeenCalledWith('/tmp/new-dir');
  });

  it('does not commit when the folder picker is cancelled', async () => {
    const onChange = vi.fn().mockResolvedValue(undefined);
    const onBrowse = vi.fn().mockResolvedValue(null);
    render(
      <ChatWorkspacePicker
        value="/tmp/ws"
        onChange={onChange}
        onBrowse={onBrowse}
        onOpen={vi.fn()}
      />,
    );
    fireEvent.click(screen.getByTestId('chat-workspace-picker-trigger'));
    await act(async () => {
      fireEvent.click(screen.getByTestId('chat-workspace-picker-browse'));
    });
    expect(onBrowse).toHaveBeenCalledTimes(1);
    expect(onChange).not.toHaveBeenCalled();
  });

  it('resets to auto-generated by committing an empty string', async () => {
    const onChange = vi.fn().mockResolvedValue(undefined);
    render(
      <ChatWorkspacePicker value="/tmp/ws" onChange={onChange} onBrowse={noop} onOpen={vi.fn()} />,
    );
    fireEvent.click(screen.getByTestId('chat-workspace-picker-trigger'));
    await act(async () => {
      fireEvent.click(screen.getByTestId('chat-workspace-picker-reset'));
    });
    expect(onChange).toHaveBeenCalledWith('');
  });

  it('reveals the current directory via onOpen', async () => {
    const onOpen = vi.fn().mockResolvedValue(undefined);
    render(
      <ChatWorkspacePicker value="/tmp/ws" onChange={vi.fn()} onBrowse={noop} onOpen={onOpen} />,
    );
    fireEvent.click(screen.getByTestId('chat-workspace-picker-trigger'));
    await act(async () => {
      fireEvent.click(screen.getByTestId('chat-workspace-picker-open'));
    });
    expect(onOpen).toHaveBeenCalledWith('/tmp/ws');
  });

  it('hides Open in Finder and Reset when no workspace is set', () => {
    render(
      <ChatWorkspacePicker value={undefined} onChange={vi.fn()} onBrowse={noop} onOpen={vi.fn()} />,
    );
    fireEvent.click(screen.getByTestId('chat-workspace-picker-trigger'));
    expect(screen.getByTestId('chat-workspace-picker-browse')).toBeInTheDocument();
    expect(screen.queryByTestId('chat-workspace-picker-open')).not.toBeInTheDocument();
    expect(screen.queryByTestId('chat-workspace-picker-reset')).not.toBeInTheDocument();
  });

  it('closes on Escape', () => {
    render(
      <ChatWorkspacePicker value="/tmp/ws" onChange={vi.fn()} onBrowse={noop} onOpen={vi.fn()} />,
    );
    fireEvent.click(screen.getByTestId('chat-workspace-picker-trigger'));
    expect(screen.getByTestId('chat-workspace-picker-menu')).toBeInTheDocument();
    fireEvent.keyDown(document, { key: 'Escape' });
    expect(screen.queryByTestId('chat-workspace-picker-menu')).not.toBeInTheDocument();
  });
});
