import type { PetSprite } from './types.js';

/**
 * Cat palette. Every char used in `grid` (except '.' transparent and 'C' the
 * mood-recolored collar) must appear here.
 *   f = fur (warm orange tabby)      F = fur stripe / shadow (darker orange)
 *   l = light cream (chest, muzzle)  e = dark outline + eyes
 *   n = nose (pink)                  i = inner ear (pink)
 *   w = eye / muzzle highlight (white)
 */
const palette = {
  f: '#f2933c',
  F: '#c96a1b',
  l: '#ffe9c9',
  e: '#3a2a1c',
  n: '#d4708a',
  i: '#f0a9b8',
  w: '#ffffff',
} satisfies Record<string, string>;

/** Authored sitting-cat art on a 2px grid (56 wide x 63 tall). */
// biome-ignore format: pixel-art grid must stay row-aligned for readability.
const grid: readonly string[] = [
  '........................................................',
  '..............ee...................ee...................',
  '.............eFFe.................eFFe..................',
  '.............eFiFe...............eFiFe..................',
  '............eFiiiFe.............eFiiiFe.................',
  '............eFiiiiFe...........eFiiiiFe.................',
  '...........eFfiiiiFe.........eFiiiifFe..................',
  '...........eFffiiiFeeeeeeeeeeeFiiifffFe.................',
  '..........eFfffffFffffffffffffffFfffffFe................',
  '..........eFffffFfffffffffffffffffFffffFe...............',
  '.........eFffffFfffffffffffffffffffFffffFe..............',
  '.........eFfffFfffffffffffffffffffffFfffFe..............',
  '........eeFffFffffffffffffffffffffffffFfFee.............',
  '........eFffffffffffffffffffffffffffffffffe.............',
  '.......effffffffffffffffffffffffffffffffffe.............',
  '.......effffffffffffffffffffffffffffffffffe.............',
  '......effffffffffffffffffffffffffffffffffffe............',
  '......effffffFFffffffffffffffffffFFffffffffe............',
  '......effffffFFFffffffffffffffffFFFffffffffe............',
  '......effffffFFffffffffffffffffffFFfffffffffe...........',
  '.......efffffffffffffffffffffffffffffffffffe............',
  '........effffffffffffffffffffffffffffffffe..............',
  '........effffffffffffeeeefffeeeeffffffffffe.............',
  '........effffffffffffffffffffffffffffffffe..............',
  '........effffffffffffffffffffffffffffffffe..............',
  '........efffffffffffffllllllllffffffffffffe.............',
  '........efffffffffffflllnnnnlllfffffffffffe.............',
  '........effffffffffffllllnnllllfffffffffffe.............',
  '........effffffffffffllllllllllfffffffffffe.............',
  '........efffffffffffflllleellllfffffffffffe.............',
  '........efffffffffffffllllllllffffffffffffe.............',
  '........effffffffffffffffffffffffffffffffe..............',
  '.........effffffffffffffffffffffffffffffe...............',
  '.........eefffffffffffffffffffffffffffeee...............',
  '...........eeeffffffffffffffffffffeeee..................',
  '.............CCCCCCCCCCCCCCCCCCCCCCCC...................',
  '............CCCCCCCCCCCCCCCCCCCCCCCCCC..................',
  '............effffffllllllllllllffffffe..................',
  '...........efffffffllllllllllllfffffffe.................',
  '..........efffffffllllllllllllllfffffffe................',
  '..........efffffffllllllllllllllfffffffe................',
  '.........effffffffllllllllllllllffffffffe...............',
  '.........effffffffllllllllllllllffffffffe...............',
  '.........effffffffllllllllllllllffffffffe...............',
  '........efffffffffllllllllllllllfffffffffe..............',
  '........efFFFfffffllllllllllllllfffffFFFfe..............',
  '........efffffffffllllllllllllllfffffffffe..............',
  '.......effffffffffllllllllllllllffffffffffe.............',
  '.......effFFFfffffllllllllllllllfffffFFFffe.............',
  '......efffffffffffllllllllllllllfffffffffffe............',
  '......effffffffffflllllleellllllfffffffffffe............',
  '......efffFFFffffflllllleellllllfffffFFFfffe............',
  '......effffffffffflllllleellllllfffffffffffe............',
  '......effffffffffflllllleellllllfffffffffffe............',
  '......efffFFFffffflllllleellllllfffffFFFfffe............',
  '......effffffffffflllllleellllllfffffffffffe............',
  '.......efffffffffflllllleellllllffffffffffe.............',
  '........eeeeeeeeellllllleellllllleeeeefffffeeeee........',
  '................ellllllleellllllle....efffffffffe.......',
  '.................eeeeeee..eeeeeee....eFFFFFFFFFe........',
  '......................................eeeeeeeee.........',
  '........................................................',
  '........................................................',
];

export const cat: PetSprite = {
  kind: 'cat',
  name: 'Cat',
  palette,
  grid,
  moods: {
    idle: { collar: '#9aa0a6', cells: {} },
    working: {
      collar: '#3da5d9',
      cells: {
        '20,21': 'f',
        '21,21': 'e',
        '22,21': 'e',
        '23,21': 'f',
        '24,21': 'f',
        '25,21': 'f',
        '26,21': 'f',
        '27,21': 'f',
        '28,21': 'e',
        '29,21': 'e',
        '30,21': 'f',
        '31,21': 'f',
        '20,22': 'f',
        '21,22': 'w',
        '22,22': 'e',
        '23,22': 'w',
        '24,22': 'f',
        '25,22': 'f',
        '26,22': 'f',
        '27,22': 'f',
        '28,22': 'w',
        '29,22': 'e',
        '30,22': 'w',
        '31,22': 'f',
        '20,23': 'f',
        '21,23': 'w',
        '22,23': 'e',
        '23,23': 'w',
        '24,23': 'f',
        '25,23': 'f',
        '26,23': 'f',
        '27,23': 'f',
        '28,23': 'w',
        '29,23': 'e',
        '30,23': 'w',
        '31,23': 'f',
        '20,24': 'f',
        '21,24': 'e',
        '22,24': 'e',
        '23,24': 'f',
        '24,24': 'f',
        '25,24': 'f',
        '26,24': 'f',
        '27,24': 'f',
        '28,24': 'e',
        '29,24': 'e',
        '30,24': 'f',
        '31,24': 'f',
      },
      pulse: true,
    },
    needs: {
      collar: '#f5c518',
      cells: {
        '20,21': 'f',
        '21,21': 'e',
        '22,21': 'w',
        '23,21': 'e',
        '24,21': 'f',
        '25,21': 'f',
        '26,21': 'f',
        '27,21': 'f',
        '28,21': 'e',
        '29,21': 'w',
        '30,21': 'e',
        '31,21': 'f',
        '20,22': 'f',
        '21,22': 'w',
        '22,22': 'e',
        '23,22': 'w',
        '24,22': 'f',
        '25,22': 'f',
        '26,22': 'f',
        '27,22': 'f',
        '28,22': 'w',
        '29,22': 'e',
        '30,22': 'w',
        '31,22': 'f',
        '20,23': 'f',
        '21,23': 'w',
        '22,23': 'e',
        '23,23': 'w',
        '24,23': 'f',
        '25,23': 'f',
        '26,23': 'f',
        '27,23': 'f',
        '28,23': 'w',
        '29,23': 'e',
        '30,23': 'w',
        '31,23': 'f',
        '20,24': 'f',
        '21,24': 'w',
        '22,24': 'w',
        '23,24': 'w',
        '24,24': 'f',
        '25,24': 'f',
        '26,24': 'f',
        '27,24': 'f',
        '28,24': 'w',
        '29,24': 'w',
        '30,24': 'w',
        '31,24': 'f',
      },
    },
    done: {
      collar: '#34c759',
      cells: {
        '20,21': 'f',
        '21,21': 'f',
        '22,21': 'f',
        '23,21': 'f',
        '24,21': 'f',
        '25,21': 'f',
        '26,21': 'f',
        '27,21': 'f',
        '28,21': 'f',
        '29,21': 'f',
        '30,21': 'f',
        '31,21': 'f',
        '20,22': 'f',
        '21,22': 'f',
        '22,22': 'e',
        '23,22': 'f',
        '24,22': 'f',
        '25,22': 'f',
        '26,22': 'f',
        '27,22': 'f',
        '28,22': 'f',
        '29,22': 'e',
        '30,22': 'f',
        '31,22': 'f',
        '20,23': 'f',
        '21,23': 'e',
        '22,23': 'f',
        '23,23': 'e',
        '24,23': 'f',
        '25,23': 'f',
        '26,23': 'f',
        '27,23': 'f',
        '28,23': 'e',
        '29,23': 'f',
        '30,23': 'e',
        '31,23': 'f',
        '20,24': 'f',
        '21,24': 'f',
        '22,24': 'f',
        '23,24': 'f',
        '24,24': 'f',
        '25,24': 'f',
        '26,24': 'f',
        '27,24': 'f',
        '28,24': 'f',
        '29,24': 'f',
        '30,24': 'f',
        '31,24': 'f',
      },
    },
    error: {
      collar: '#f87171',
      cells: {
        '20,21': 'f',
        '21,21': 'e',
        '22,21': 'w',
        '23,21': 'e',
        '24,21': 'f',
        '25,21': 'f',
        '26,21': 'f',
        '27,21': 'f',
        '28,21': 'e',
        '29,21': 'w',
        '30,21': 'e',
        '31,21': 'f',
        '20,22': 'f',
        '21,22': 'w',
        '22,22': 'e',
        '23,22': 'w',
        '24,22': 'f',
        '25,22': 'f',
        '26,22': 'f',
        '27,22': 'f',
        '28,22': 'w',
        '29,22': 'e',
        '30,22': 'w',
        '31,22': 'f',
        '20,23': 'f',
        '21,23': 'w',
        '22,23': 'e',
        '23,23': 'w',
        '24,23': 'f',
        '25,23': 'f',
        '26,23': 'f',
        '27,23': 'f',
        '28,23': 'w',
        '29,23': 'e',
        '30,23': 'w',
        '31,23': 'f',
        '20,24': 'f',
        '21,24': 'w',
        '22,24': 'w',
        '23,24': 'w',
        '24,24': 'f',
        '25,24': 'f',
        '26,24': 'f',
        '27,24': 'f',
        '28,24': 'w',
        '29,24': 'w',
        '30,24': 'w',
        '31,24': 'f',
        '22,20': 'w',
        '29,20': 'w',
      },
    },
  },
};
