import type { PetKind } from '../../../../shared/ipc.js';

/** All selectable pets, in picker display order. */
export const PET_KINDS: readonly PetKind[] = [
  'astronaut',
  'bear',
  'beauty-guru',
  'bigfoot',
  'bollywood-star',
  'cat',
  'chef',
  'dog',
  'fitness-influencer',
  'fortune-god',
  'knight',
  'lion',
  'maneki-neko',
  'merlion',
  'ninja',
  'pig',
  'pirate',
  'quokka',
  'rabbit',
  'red-panda',
  'robot',
  'royal-guard',
  'streamer',
  'tech-reviewer',
  'travel-vlogger',
  'unicorn',
  'wizard',
  'wok-uncle',
  'sous-chef',
  'pastry-chef',
  'sushi-chef',
  'butcher',
  'dishwasher',
  'boss',
  'accountant',
  'intern',
  'it-support',
  'receptionist',
  'waiter',
  'barista',
  'sommelier',
  'bartender',
  'hostess',
  'sergeant',
  'scout',
  'combat-medic',
  'radio-operator',
  'general',
  'police-officer',
  'detective',
  'k9-handler',
  'swat',
  'police-chief',
  'firefighter',
  'fire-chief',
  'ladder-firefighter',
  'rookie-firefighter',
  'fire-dalmatian',
  'baker',
  'blacksmith',
  'fisherman',
  'shepherd',
  'town-crier',
  'farmer',
  'dairy-farmer',
  'fruit-picker',
  'beekeeper',
  'scarecrow',
];

/** Pet used when the stored value is unset or invalid. */
export const DEFAULT_PET: PetKind = 'red-panda';
