/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnderTheHoodRouteImport } from './routes/under-the-hood'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as DeployRouteImport } from './routes/deploy'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as AgentsIndexRouteImport } from './routes/agents/index'
import { Route as SettingsPluginsRouteImport } from './routes/settings/plugins'
import { Route as SettingsDevicesRouteImport } from './routes/settings/devices'
import { Route as SettingsConnectorsRouteImport } from './routes/settings/connectors'
import { Route as SettingsAiProvidersRouteImport } from './routes/settings/ai-providers'
import { Route as SettingsAgentDefaultsRouteImport } from './routes/settings/agent-defaults'
import { Route as ProjectsMyWorkRouteImport } from './routes/projects/my-work'
import { Route as ProjectsListRouteImport } from './routes/projects/list'
import { Route as ProjectsKanbanRouteImport } from './routes/projects/kanban'
import { Route as ProjectsInboxRouteImport } from './routes/projects/inbox'
import { Route as ProjectsAllRouteImport } from './routes/projects/all'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects/$projectId'
import { Route as AgentsIdRouteImport } from './routes/agents/$id'
import { Route as SettingsMessagingAppsIndexRouteImport } from './routes/settings/messaging-apps/index'
import { Route as SettingsMessagingAppsNewWhatsappRouteImport } from './routes/settings/messaging-apps/new-whatsapp'
import { Route as SettingsMessagingAppsNewTelegramRouteImport } from './routes/settings/messaging-apps/new-telegram'
import { Route as SettingsMessagingAppsIdRouteImport } from './routes/settings/messaging-apps/$id'
import { Route as ProjectsIssuesIssueIdRouteImport } from './routes/projects/issues.$issueId'

const UnderTheHoodRoute = UnderTheHoodRouteImport.update({
  id: '/under-the-hood',
  path: '/under-the-hood',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const DeployRoute = DeployRouteImport.update({
  id: '/deploy',
  path: '/deploy',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsRoute,
} as any)
const AgentsIndexRoute = AgentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AgentsRoute,
} as any)
const SettingsPluginsRoute = SettingsPluginsRouteImport.update({
  id: '/plugins',
  path: '/plugins',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsDevicesRoute = SettingsDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsConnectorsRoute = SettingsConnectorsRouteImport.update({
  id: '/connectors',
  path: '/connectors',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAiProvidersRoute = SettingsAiProvidersRouteImport.update({
  id: '/ai-providers',
  path: '/ai-providers',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAgentDefaultsRoute = SettingsAgentDefaultsRouteImport.update({
  id: '/agent-defaults',
  path: '/agent-defaults',
  getParentRoute: () => SettingsRoute,
} as any)
const ProjectsMyWorkRoute = ProjectsMyWorkRouteImport.update({
  id: '/my-work',
  path: '/my-work',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsListRoute = ProjectsListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsKanbanRoute = ProjectsKanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsInboxRoute = ProjectsInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsAllRoute = ProjectsAllRouteImport.update({
  id: '/all',
  path: '/all',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => ProjectsRoute,
} as any)
const AgentsIdRoute = AgentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AgentsRoute,
} as any)
const SettingsMessagingAppsIndexRoute =
  SettingsMessagingAppsIndexRouteImport.update({
    id: '/messaging-apps/',
    path: '/messaging-apps/',
    getParentRoute: () => SettingsRoute,
  } as any)
const SettingsMessagingAppsNewWhatsappRoute =
  SettingsMessagingAppsNewWhatsappRouteImport.update({
    id: '/messaging-apps/new-whatsapp',
    path: '/messaging-apps/new-whatsapp',
    getParentRoute: () => SettingsRoute,
  } as any)
const SettingsMessagingAppsNewTelegramRoute =
  SettingsMessagingAppsNewTelegramRouteImport.update({
    id: '/messaging-apps/new-telegram',
    path: '/messaging-apps/new-telegram',
    getParentRoute: () => SettingsRoute,
  } as any)
const SettingsMessagingAppsIdRoute = SettingsMessagingAppsIdRouteImport.update({
  id: '/messaging-apps/$id',
  path: '/messaging-apps/$id',
  getParentRoute: () => SettingsRoute,
} as any)
const ProjectsIssuesIssueIdRoute = ProjectsIssuesIssueIdRouteImport.update({
  id: '/issues/$issueId',
  path: '/issues/$issueId',
  getParentRoute: () => ProjectsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRouteWithChildren
  '/chat': typeof ChatRoute
  '/deploy': typeof DeployRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/under-the-hood': typeof UnderTheHoodRoute
  '/agents/$id': typeof AgentsIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/projects/all': typeof ProjectsAllRoute
  '/projects/inbox': typeof ProjectsInboxRoute
  '/projects/kanban': typeof ProjectsKanbanRoute
  '/projects/list': typeof ProjectsListRoute
  '/projects/my-work': typeof ProjectsMyWorkRoute
  '/settings/agent-defaults': typeof SettingsAgentDefaultsRoute
  '/settings/ai-providers': typeof SettingsAiProvidersRoute
  '/settings/connectors': typeof SettingsConnectorsRoute
  '/settings/devices': typeof SettingsDevicesRoute
  '/settings/plugins': typeof SettingsPluginsRoute
  '/agents/': typeof AgentsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/projects/issues/$issueId': typeof ProjectsIssuesIssueIdRoute
  '/settings/messaging-apps/$id': typeof SettingsMessagingAppsIdRoute
  '/settings/messaging-apps/new-telegram': typeof SettingsMessagingAppsNewTelegramRoute
  '/settings/messaging-apps/new-whatsapp': typeof SettingsMessagingAppsNewWhatsappRoute
  '/settings/messaging-apps/': typeof SettingsMessagingAppsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/deploy': typeof DeployRoute
  '/under-the-hood': typeof UnderTheHoodRoute
  '/agents/$id': typeof AgentsIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/projects/all': typeof ProjectsAllRoute
  '/projects/inbox': typeof ProjectsInboxRoute
  '/projects/kanban': typeof ProjectsKanbanRoute
  '/projects/list': typeof ProjectsListRoute
  '/projects/my-work': typeof ProjectsMyWorkRoute
  '/settings/agent-defaults': typeof SettingsAgentDefaultsRoute
  '/settings/ai-providers': typeof SettingsAiProvidersRoute
  '/settings/connectors': typeof SettingsConnectorsRoute
  '/settings/devices': typeof SettingsDevicesRoute
  '/settings/plugins': typeof SettingsPluginsRoute
  '/agents': typeof AgentsIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/projects/issues/$issueId': typeof ProjectsIssuesIssueIdRoute
  '/settings/messaging-apps/$id': typeof SettingsMessagingAppsIdRoute
  '/settings/messaging-apps/new-telegram': typeof SettingsMessagingAppsNewTelegramRoute
  '/settings/messaging-apps/new-whatsapp': typeof SettingsMessagingAppsNewWhatsappRoute
  '/settings/messaging-apps': typeof SettingsMessagingAppsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRouteWithChildren
  '/chat': typeof ChatRoute
  '/deploy': typeof DeployRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/under-the-hood': typeof UnderTheHoodRoute
  '/agents/$id': typeof AgentsIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/projects/all': typeof ProjectsAllRoute
  '/projects/inbox': typeof ProjectsInboxRoute
  '/projects/kanban': typeof ProjectsKanbanRoute
  '/projects/list': typeof ProjectsListRoute
  '/projects/my-work': typeof ProjectsMyWorkRoute
  '/settings/agent-defaults': typeof SettingsAgentDefaultsRoute
  '/settings/ai-providers': typeof SettingsAiProvidersRoute
  '/settings/connectors': typeof SettingsConnectorsRoute
  '/settings/devices': typeof SettingsDevicesRoute
  '/settings/plugins': typeof SettingsPluginsRoute
  '/agents/': typeof AgentsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/projects/issues/$issueId': typeof ProjectsIssuesIssueIdRoute
  '/settings/messaging-apps/$id': typeof SettingsMessagingAppsIdRoute
  '/settings/messaging-apps/new-telegram': typeof SettingsMessagingAppsNewTelegramRoute
  '/settings/messaging-apps/new-whatsapp': typeof SettingsMessagingAppsNewWhatsappRoute
  '/settings/messaging-apps/': typeof SettingsMessagingAppsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/chat'
    | '/deploy'
    | '/projects'
    | '/settings'
    | '/under-the-hood'
    | '/agents/$id'
    | '/projects/$projectId'
    | '/projects/all'
    | '/projects/inbox'
    | '/projects/kanban'
    | '/projects/list'
    | '/projects/my-work'
    | '/settings/agent-defaults'
    | '/settings/ai-providers'
    | '/settings/connectors'
    | '/settings/devices'
    | '/settings/plugins'
    | '/agents/'
    | '/projects/'
    | '/settings/'
    | '/projects/issues/$issueId'
    | '/settings/messaging-apps/$id'
    | '/settings/messaging-apps/new-telegram'
    | '/settings/messaging-apps/new-whatsapp'
    | '/settings/messaging-apps/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/deploy'
    | '/under-the-hood'
    | '/agents/$id'
    | '/projects/$projectId'
    | '/projects/all'
    | '/projects/inbox'
    | '/projects/kanban'
    | '/projects/list'
    | '/projects/my-work'
    | '/settings/agent-defaults'
    | '/settings/ai-providers'
    | '/settings/connectors'
    | '/settings/devices'
    | '/settings/plugins'
    | '/agents'
    | '/projects'
    | '/settings'
    | '/projects/issues/$issueId'
    | '/settings/messaging-apps/$id'
    | '/settings/messaging-apps/new-telegram'
    | '/settings/messaging-apps/new-whatsapp'
    | '/settings/messaging-apps'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/chat'
    | '/deploy'
    | '/projects'
    | '/settings'
    | '/under-the-hood'
    | '/agents/$id'
    | '/projects/$projectId'
    | '/projects/all'
    | '/projects/inbox'
    | '/projects/kanban'
    | '/projects/list'
    | '/projects/my-work'
    | '/settings/agent-defaults'
    | '/settings/ai-providers'
    | '/settings/connectors'
    | '/settings/devices'
    | '/settings/plugins'
    | '/agents/'
    | '/projects/'
    | '/settings/'
    | '/projects/issues/$issueId'
    | '/settings/messaging-apps/$id'
    | '/settings/messaging-apps/new-telegram'
    | '/settings/messaging-apps/new-whatsapp'
    | '/settings/messaging-apps/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRouteWithChildren
  ChatRoute: typeof ChatRoute
  DeployRoute: typeof DeployRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  SettingsRoute: typeof SettingsRouteWithChildren
  UnderTheHoodRoute: typeof UnderTheHoodRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/under-the-hood': {
      id: '/under-the-hood'
      path: '/under-the-hood'
      fullPath: '/under-the-hood'
      preLoaderRoute: typeof UnderTheHoodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deploy': {
      id: '/deploy'
      path: '/deploy'
      fullPath: '/deploy'
      preLoaderRoute: typeof DeployRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/projects/': {
      id: '/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/agents/': {
      id: '/agents/'
      path: '/'
      fullPath: '/agents/'
      preLoaderRoute: typeof AgentsIndexRouteImport
      parentRoute: typeof AgentsRoute
    }
    '/settings/plugins': {
      id: '/settings/plugins'
      path: '/plugins'
      fullPath: '/settings/plugins'
      preLoaderRoute: typeof SettingsPluginsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/devices': {
      id: '/settings/devices'
      path: '/devices'
      fullPath: '/settings/devices'
      preLoaderRoute: typeof SettingsDevicesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/connectors': {
      id: '/settings/connectors'
      path: '/connectors'
      fullPath: '/settings/connectors'
      preLoaderRoute: typeof SettingsConnectorsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/ai-providers': {
      id: '/settings/ai-providers'
      path: '/ai-providers'
      fullPath: '/settings/ai-providers'
      preLoaderRoute: typeof SettingsAiProvidersRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/agent-defaults': {
      id: '/settings/agent-defaults'
      path: '/agent-defaults'
      fullPath: '/settings/agent-defaults'
      preLoaderRoute: typeof SettingsAgentDefaultsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/projects/my-work': {
      id: '/projects/my-work'
      path: '/my-work'
      fullPath: '/projects/my-work'
      preLoaderRoute: typeof ProjectsMyWorkRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/list': {
      id: '/projects/list'
      path: '/list'
      fullPath: '/projects/list'
      preLoaderRoute: typeof ProjectsListRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/kanban': {
      id: '/projects/kanban'
      path: '/kanban'
      fullPath: '/projects/kanban'
      preLoaderRoute: typeof ProjectsKanbanRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/inbox': {
      id: '/projects/inbox'
      path: '/inbox'
      fullPath: '/projects/inbox'
      preLoaderRoute: typeof ProjectsInboxRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/all': {
      id: '/projects/all'
      path: '/all'
      fullPath: '/projects/all'
      preLoaderRoute: typeof ProjectsAllRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/agents/$id': {
      id: '/agents/$id'
      path: '/$id'
      fullPath: '/agents/$id'
      preLoaderRoute: typeof AgentsIdRouteImport
      parentRoute: typeof AgentsRoute
    }
    '/settings/messaging-apps/': {
      id: '/settings/messaging-apps/'
      path: '/messaging-apps'
      fullPath: '/settings/messaging-apps/'
      preLoaderRoute: typeof SettingsMessagingAppsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/messaging-apps/new-whatsapp': {
      id: '/settings/messaging-apps/new-whatsapp'
      path: '/messaging-apps/new-whatsapp'
      fullPath: '/settings/messaging-apps/new-whatsapp'
      preLoaderRoute: typeof SettingsMessagingAppsNewWhatsappRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/messaging-apps/new-telegram': {
      id: '/settings/messaging-apps/new-telegram'
      path: '/messaging-apps/new-telegram'
      fullPath: '/settings/messaging-apps/new-telegram'
      preLoaderRoute: typeof SettingsMessagingAppsNewTelegramRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/messaging-apps/$id': {
      id: '/settings/messaging-apps/$id'
      path: '/messaging-apps/$id'
      fullPath: '/settings/messaging-apps/$id'
      preLoaderRoute: typeof SettingsMessagingAppsIdRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/projects/issues/$issueId': {
      id: '/projects/issues/$issueId'
      path: '/issues/$issueId'
      fullPath: '/projects/issues/$issueId'
      preLoaderRoute: typeof ProjectsIssuesIssueIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
  }
}

interface AgentsRouteChildren {
  AgentsIdRoute: typeof AgentsIdRoute
  AgentsIndexRoute: typeof AgentsIndexRoute
}

const AgentsRouteChildren: AgentsRouteChildren = {
  AgentsIdRoute: AgentsIdRoute,
  AgentsIndexRoute: AgentsIndexRoute,
}

const AgentsRouteWithChildren =
  AgentsRoute._addFileChildren(AgentsRouteChildren)

interface ProjectsRouteChildren {
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
  ProjectsAllRoute: typeof ProjectsAllRoute
  ProjectsInboxRoute: typeof ProjectsInboxRoute
  ProjectsKanbanRoute: typeof ProjectsKanbanRoute
  ProjectsListRoute: typeof ProjectsListRoute
  ProjectsMyWorkRoute: typeof ProjectsMyWorkRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ProjectsIssuesIssueIdRoute: typeof ProjectsIssuesIssueIdRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
  ProjectsAllRoute: ProjectsAllRoute,
  ProjectsInboxRoute: ProjectsInboxRoute,
  ProjectsKanbanRoute: ProjectsKanbanRoute,
  ProjectsListRoute: ProjectsListRoute,
  ProjectsMyWorkRoute: ProjectsMyWorkRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  ProjectsIssuesIssueIdRoute: ProjectsIssuesIssueIdRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

interface SettingsRouteChildren {
  SettingsAgentDefaultsRoute: typeof SettingsAgentDefaultsRoute
  SettingsAiProvidersRoute: typeof SettingsAiProvidersRoute
  SettingsConnectorsRoute: typeof SettingsConnectorsRoute
  SettingsDevicesRoute: typeof SettingsDevicesRoute
  SettingsPluginsRoute: typeof SettingsPluginsRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  SettingsMessagingAppsIdRoute: typeof SettingsMessagingAppsIdRoute
  SettingsMessagingAppsNewTelegramRoute: typeof SettingsMessagingAppsNewTelegramRoute
  SettingsMessagingAppsNewWhatsappRoute: typeof SettingsMessagingAppsNewWhatsappRoute
  SettingsMessagingAppsIndexRoute: typeof SettingsMessagingAppsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAgentDefaultsRoute: SettingsAgentDefaultsRoute,
  SettingsAiProvidersRoute: SettingsAiProvidersRoute,
  SettingsConnectorsRoute: SettingsConnectorsRoute,
  SettingsDevicesRoute: SettingsDevicesRoute,
  SettingsPluginsRoute: SettingsPluginsRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  SettingsMessagingAppsIdRoute: SettingsMessagingAppsIdRoute,
  SettingsMessagingAppsNewTelegramRoute: SettingsMessagingAppsNewTelegramRoute,
  SettingsMessagingAppsNewWhatsappRoute: SettingsMessagingAppsNewWhatsappRoute,
  SettingsMessagingAppsIndexRoute: SettingsMessagingAppsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRouteWithChildren,
  ChatRoute: ChatRoute,
  DeployRoute: DeployRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  SettingsRoute: SettingsRouteWithChildren,
  UnderTheHoodRoute: UnderTheHoodRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
