/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebSearchRouteImport } from './routes/web-search'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as MessagingAppsRouteImport } from './routes/messaging-apps'
import { Route as DeployRouteImport } from './routes/deploy'
import { Route as ConnectorsRouteImport } from './routes/connectors'
import { Route as ConnectionsRouteImport } from './routes/connections'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MessagingAppsIndexRouteImport } from './routes/messaging-apps/index'
import { Route as AgentsIndexRouteImport } from './routes/agents/index'
import { Route as MessagingAppsNewWhatsappRouteImport } from './routes/messaging-apps/new-whatsapp'
import { Route as MessagingAppsNewTelegramRouteImport } from './routes/messaging-apps/new-telegram'
import { Route as MessagingAppsIdRouteImport } from './routes/messaging-apps/$id'
import { Route as AgentsIdRouteImport } from './routes/agents/$id'

const WebSearchRoute = WebSearchRouteImport.update({
  id: '/web-search',
  path: '/web-search',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagingAppsRoute = MessagingAppsRouteImport.update({
  id: '/messaging-apps',
  path: '/messaging-apps',
  getParentRoute: () => rootRouteImport,
} as any)
const DeployRoute = DeployRouteImport.update({
  id: '/deploy',
  path: '/deploy',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectorsRoute = ConnectorsRouteImport.update({
  id: '/connectors',
  path: '/connectors',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectionsRoute = ConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagingAppsIndexRoute = MessagingAppsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MessagingAppsRoute,
} as any)
const AgentsIndexRoute = AgentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AgentsRoute,
} as any)
const MessagingAppsNewWhatsappRoute =
  MessagingAppsNewWhatsappRouteImport.update({
    id: '/new-whatsapp',
    path: '/new-whatsapp',
    getParentRoute: () => MessagingAppsRoute,
  } as any)
const MessagingAppsNewTelegramRoute =
  MessagingAppsNewTelegramRouteImport.update({
    id: '/new-telegram',
    path: '/new-telegram',
    getParentRoute: () => MessagingAppsRoute,
  } as any)
const MessagingAppsIdRoute = MessagingAppsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MessagingAppsRoute,
} as any)
const AgentsIdRoute = AgentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AgentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRouteWithChildren
  '/chat': typeof ChatRoute
  '/connections': typeof ConnectionsRoute
  '/connectors': typeof ConnectorsRoute
  '/deploy': typeof DeployRoute
  '/messaging-apps': typeof MessagingAppsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/web-search': typeof WebSearchRoute
  '/agents/$id': typeof AgentsIdRoute
  '/messaging-apps/$id': typeof MessagingAppsIdRoute
  '/messaging-apps/new-telegram': typeof MessagingAppsNewTelegramRoute
  '/messaging-apps/new-whatsapp': typeof MessagingAppsNewWhatsappRoute
  '/agents/': typeof AgentsIndexRoute
  '/messaging-apps/': typeof MessagingAppsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/connections': typeof ConnectionsRoute
  '/connectors': typeof ConnectorsRoute
  '/deploy': typeof DeployRoute
  '/settings': typeof SettingsRoute
  '/web-search': typeof WebSearchRoute
  '/agents/$id': typeof AgentsIdRoute
  '/messaging-apps/$id': typeof MessagingAppsIdRoute
  '/messaging-apps/new-telegram': typeof MessagingAppsNewTelegramRoute
  '/messaging-apps/new-whatsapp': typeof MessagingAppsNewWhatsappRoute
  '/agents': typeof AgentsIndexRoute
  '/messaging-apps': typeof MessagingAppsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRouteWithChildren
  '/chat': typeof ChatRoute
  '/connections': typeof ConnectionsRoute
  '/connectors': typeof ConnectorsRoute
  '/deploy': typeof DeployRoute
  '/messaging-apps': typeof MessagingAppsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/web-search': typeof WebSearchRoute
  '/agents/$id': typeof AgentsIdRoute
  '/messaging-apps/$id': typeof MessagingAppsIdRoute
  '/messaging-apps/new-telegram': typeof MessagingAppsNewTelegramRoute
  '/messaging-apps/new-whatsapp': typeof MessagingAppsNewWhatsappRoute
  '/agents/': typeof AgentsIndexRoute
  '/messaging-apps/': typeof MessagingAppsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/chat'
    | '/connections'
    | '/connectors'
    | '/deploy'
    | '/messaging-apps'
    | '/settings'
    | '/web-search'
    | '/agents/$id'
    | '/messaging-apps/$id'
    | '/messaging-apps/new-telegram'
    | '/messaging-apps/new-whatsapp'
    | '/agents/'
    | '/messaging-apps/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/connections'
    | '/connectors'
    | '/deploy'
    | '/settings'
    | '/web-search'
    | '/agents/$id'
    | '/messaging-apps/$id'
    | '/messaging-apps/new-telegram'
    | '/messaging-apps/new-whatsapp'
    | '/agents'
    | '/messaging-apps'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/chat'
    | '/connections'
    | '/connectors'
    | '/deploy'
    | '/messaging-apps'
    | '/settings'
    | '/web-search'
    | '/agents/$id'
    | '/messaging-apps/$id'
    | '/messaging-apps/new-telegram'
    | '/messaging-apps/new-whatsapp'
    | '/agents/'
    | '/messaging-apps/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRouteWithChildren
  ChatRoute: typeof ChatRoute
  ConnectionsRoute: typeof ConnectionsRoute
  ConnectorsRoute: typeof ConnectorsRoute
  DeployRoute: typeof DeployRoute
  MessagingAppsRoute: typeof MessagingAppsRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  WebSearchRoute: typeof WebSearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/web-search': {
      id: '/web-search'
      path: '/web-search'
      fullPath: '/web-search'
      preLoaderRoute: typeof WebSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messaging-apps': {
      id: '/messaging-apps'
      path: '/messaging-apps'
      fullPath: '/messaging-apps'
      preLoaderRoute: typeof MessagingAppsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deploy': {
      id: '/deploy'
      path: '/deploy'
      fullPath: '/deploy'
      preLoaderRoute: typeof DeployRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connectors': {
      id: '/connectors'
      path: '/connectors'
      fullPath: '/connectors'
      preLoaderRoute: typeof ConnectorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connections': {
      id: '/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof ConnectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messaging-apps/': {
      id: '/messaging-apps/'
      path: '/'
      fullPath: '/messaging-apps/'
      preLoaderRoute: typeof MessagingAppsIndexRouteImport
      parentRoute: typeof MessagingAppsRoute
    }
    '/agents/': {
      id: '/agents/'
      path: '/'
      fullPath: '/agents/'
      preLoaderRoute: typeof AgentsIndexRouteImport
      parentRoute: typeof AgentsRoute
    }
    '/messaging-apps/new-whatsapp': {
      id: '/messaging-apps/new-whatsapp'
      path: '/new-whatsapp'
      fullPath: '/messaging-apps/new-whatsapp'
      preLoaderRoute: typeof MessagingAppsNewWhatsappRouteImport
      parentRoute: typeof MessagingAppsRoute
    }
    '/messaging-apps/new-telegram': {
      id: '/messaging-apps/new-telegram'
      path: '/new-telegram'
      fullPath: '/messaging-apps/new-telegram'
      preLoaderRoute: typeof MessagingAppsNewTelegramRouteImport
      parentRoute: typeof MessagingAppsRoute
    }
    '/messaging-apps/$id': {
      id: '/messaging-apps/$id'
      path: '/$id'
      fullPath: '/messaging-apps/$id'
      preLoaderRoute: typeof MessagingAppsIdRouteImport
      parentRoute: typeof MessagingAppsRoute
    }
    '/agents/$id': {
      id: '/agents/$id'
      path: '/$id'
      fullPath: '/agents/$id'
      preLoaderRoute: typeof AgentsIdRouteImport
      parentRoute: typeof AgentsRoute
    }
  }
}

interface AgentsRouteChildren {
  AgentsIdRoute: typeof AgentsIdRoute
  AgentsIndexRoute: typeof AgentsIndexRoute
}

const AgentsRouteChildren: AgentsRouteChildren = {
  AgentsIdRoute: AgentsIdRoute,
  AgentsIndexRoute: AgentsIndexRoute,
}

const AgentsRouteWithChildren =
  AgentsRoute._addFileChildren(AgentsRouteChildren)

interface MessagingAppsRouteChildren {
  MessagingAppsIdRoute: typeof MessagingAppsIdRoute
  MessagingAppsNewTelegramRoute: typeof MessagingAppsNewTelegramRoute
  MessagingAppsNewWhatsappRoute: typeof MessagingAppsNewWhatsappRoute
  MessagingAppsIndexRoute: typeof MessagingAppsIndexRoute
}

const MessagingAppsRouteChildren: MessagingAppsRouteChildren = {
  MessagingAppsIdRoute: MessagingAppsIdRoute,
  MessagingAppsNewTelegramRoute: MessagingAppsNewTelegramRoute,
  MessagingAppsNewWhatsappRoute: MessagingAppsNewWhatsappRoute,
  MessagingAppsIndexRoute: MessagingAppsIndexRoute,
}

const MessagingAppsRouteWithChildren = MessagingAppsRoute._addFileChildren(
  MessagingAppsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRouteWithChildren,
  ChatRoute: ChatRoute,
  ConnectionsRoute: ConnectionsRoute,
  ConnectorsRoute: ConnectorsRoute,
  DeployRoute: DeployRoute,
  MessagingAppsRoute: MessagingAppsRouteWithChildren,
  SettingsRoute: SettingsRoute,
  WebSearchRoute: WebSearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
