import type { FilteredModel } from './types.js';

/**
 * Curated bootstrap model list returned by the gateway when **no provider
 * credentials are configured at all**. Used purely for discoverability —
 * gives MC's deploy form something to render so the user can see what
 * models would be available if they added credentials.
 *
 * The moment ANY credential is configured, the gateway switches to live
 * fetching and this list is no longer returned. Models in this list can't
 * actually be used until the matching credential exists.
 *
 * **This file is auto-generated by `scripts/audit-models.ts --apply`** —
 * the audit script picks the top tier-N model per provider from live API
 * responses (typically flagship + mid + budget = ~3 per provider). Manual
 * edits are accepted as the initial seed; subsequent audits will overwrite.
 *
 * Anthropic entries re-verified against live api.anthropic.com/v1/models on
 * 2026-06-20 (flagship is now claude-opus-4-8). OpenAI entries were NOT
 * re-verified on 2026-06-20 — the Codex backend token was expired (401), so
 * these are carried forward from the 2026-04-13 audit: gpt-5.4 was confirmed
 * via the ChatGPT/Codex backend then; o3-pro and gpt-4o are placeholders the
 * Codex backend doesn't expose but are real public OpenAI models reachable
 * via a classic sk- key. Google entries are placeholders pending working
 * credentials.
 */
export const BOOTSTRAP_MODELS: FilteredModel[] = [
  // Anthropic — re-verified against live API 2026-06-20
  {
    value: 'anthropic/claude-opus-4-8',
    label: 'Claude Opus 4.8',
    provider: 'anthropic',
  },
  {
    value: 'anthropic/claude-sonnet-4-6',
    label: 'Claude Sonnet 4.6',
    provider: 'anthropic',
  },
  {
    value: 'anthropic/claude-haiku-4-5-20251001',
    label: 'Claude Haiku 4.5',
    provider: 'anthropic',
  },
  // OpenAI — placeholders, NOT verified against live API
  {
    value: 'openai/o3-pro',
    label: 'o3-pro',
    provider: 'openai',
  },
  {
    value: 'openai/gpt-5.4',
    label: 'GPT-5.4',
    provider: 'openai',
  },
  {
    value: 'openai/gpt-4o',
    label: 'GPT-4o',
    provider: 'openai',
  },
  // Google — placeholders, NOT verified against live API
  {
    value: 'google/gemini-2.5-pro',
    label: 'Gemini 2.5 Pro',
    provider: 'google',
  },
  {
    value: 'google/gemini-2.5-flash',
    label: 'Gemini 2.5 Flash',
    provider: 'google',
  },
  // Moonshot (Kimi) — NOT verified against a live API key, but every id here is
  // confirmed resolvable by the pi-ai runtime (getModel('moonshotai', id) !==
  // undefined in pi-ai@0.79.8), so they are runnable, not just discoverable.
  // Run `npm run models:audit:apply` with MOONSHOT_API_KEY set to regenerate
  // against live /v1/models.
  {
    value: 'moonshotai/kimi-k2-thinking',
    label: 'Kimi K2 Thinking',
    provider: 'moonshotai',
  },
  {
    value: 'moonshotai/kimi-k2.6',
    label: 'Kimi K2.6',
    provider: 'moonshotai',
  },
  {
    value: 'moonshotai/kimi-k2-0905-preview',
    label: 'Kimi K2 (0905)',
    provider: 'moonshotai',
  },
];
