import type { FilteredModel } from './types.js';

/**
 * Curated bootstrap model list returned by the gateway when **no provider
 * credentials are configured at all**. Used purely for discoverability —
 * gives MC's deploy form something to render so the user can see what
 * models would be available if they added credentials.
 *
 * The moment ANY credential is configured, the gateway switches to live
 * fetching and this list is no longer returned. Models in this list can't
 * actually be used until the matching credential exists.
 *
 * **This file is auto-generated by `scripts/audit-models.ts --apply`** —
 * the audit script picks the top tier-N model per provider from live API
 * responses (typically flagship + mid + budget = ~3 per provider). Manual
 * edits are accepted as the initial seed; subsequent audits will overwrite.
 *
 * Anthropic entries re-verified against live api.anthropic.com/v1/models on
 * 2026-06-20 (flagship is now claude-opus-4-8). OpenAI entries re-verified on
 * 2026-06-21 via the ChatGPT/Codex backend token, which returned only
 * gpt-5.5 / gpt-5.4 / gpt-5.4-mini — the prior o3-pro and gpt-4o placeholders
 * (not exposed by the Codex backend) were dropped. Note the Codex token sees a
 * narrow slice of OpenAI's catalog; a classic sk- key would surface more.
 * Google entries are placeholders pending working credentials.
 */
export const BOOTSTRAP_MODELS: FilteredModel[] = [
  // Anthropic — re-verified against live API 2026-06-20
  {
    value: 'anthropic/claude-opus-4-8',
    label: 'Claude Opus 4.8',
    provider: 'anthropic',
  },
  {
    value: 'anthropic/claude-sonnet-4-6',
    label: 'Claude Sonnet 4.6',
    provider: 'anthropic',
  },
  {
    value: 'anthropic/claude-haiku-4-5-20251001',
    label: 'Claude Haiku 4.5',
    provider: 'anthropic',
  },
  // OpenAI — re-verified against live API 2026-06-21 (ChatGPT/Codex backend
  // token returned only gpt-5.5 / gpt-5.4 / gpt-5.4-mini). flagship + mid +
  // budget. The prior o3-pro and gpt-4o placeholders were dropped — the Codex
  // token doesn't expose them.
  {
    value: 'openai/gpt-5.5',
    label: 'GPT-5.5',
    provider: 'openai',
  },
  {
    value: 'openai/gpt-5.4',
    label: 'GPT-5.4',
    provider: 'openai',
  },
  {
    value: 'openai/gpt-5.4-mini',
    label: 'GPT-5.4-Mini',
    provider: 'openai',
  },
  // Google — placeholders, NOT verified against live API
  {
    value: 'google/gemini-2.5-pro',
    label: 'Gemini 2.5 Pro',
    provider: 'google',
  },
  {
    value: 'google/gemini-2.5-flash',
    label: 'Gemini 2.5 Flash',
    provider: 'google',
  },
  // Moonshot (Kimi) — verified against live api.moonshot.ai/v1/models on
  // 2026-06-21. Every id here is both returned by the live endpoint AND
  // resolvable by the pi-ai runtime (getModel), so they are runnable, not just
  // discoverable. Run `npm run models:audit:apply` with MOONSHOT_API_KEY set to
  // refresh.
  {
    value: 'moonshotai/kimi-k2.6',
    label: 'Kimi K2.6',
    provider: 'moonshotai',
  },
  {
    value: 'moonshotai/kimi-k2.7-code',
    label: 'Kimi K2.7 Code',
    provider: 'moonshotai',
  },
  {
    value: 'moonshotai/kimi-k2.5',
    label: 'Kimi K2.5',
    provider: 'moonshotai',
  },
];
