import type { FilteredModel } from './types.js';

/**
 * Curated bootstrap model list returned by the gateway when **no provider
 * credentials are configured at all**. Used purely for discoverability —
 * gives MC's deploy form something to render so the user can see what
 * models would be available if they added credentials.
 *
 * The moment ANY credential is configured, the gateway switches to live
 * fetching and this list is no longer returned. Models in this list can't
 * actually be used until the matching credential exists.
 *
 * **This file is auto-generated by `scripts/audit-models.ts --apply`** —
 * the audit script picks the top tier-N model per provider from live API
 * responses (typically flagship + mid + budget = ~3 per provider). Manual
 * edits are accepted as the initial seed; subsequent audits will overwrite.
 */
export const BOOTSTRAP_MODELS: FilteredModel[] = [
  // Anthropic
  {
    value: 'anthropic/claude-opus-4-5',
    label: 'Claude Opus 4.5',
    provider: 'anthropic',
  },
  {
    value: 'anthropic/claude-sonnet-4-5',
    label: 'Claude Sonnet 4.5',
    provider: 'anthropic',
  },
  {
    value: 'anthropic/claude-haiku-4-5',
    label: 'Claude Haiku 4.5',
    provider: 'anthropic',
  },
  // OpenAI
  {
    value: 'openai/o3-pro',
    label: 'o3-pro',
    provider: 'openai',
  },
  {
    value: 'openai/gpt-5.4',
    label: 'GPT-5.4',
    provider: 'openai',
  },
  {
    value: 'openai/gpt-4o',
    label: 'GPT-4o',
    provider: 'openai',
  },
  // Google
  {
    value: 'google/gemini-2.5-pro',
    label: 'Gemini 2.5 Pro',
    provider: 'google',
  },
  {
    value: 'google/gemini-2.5-flash',
    label: 'Gemini 2.5 Flash',
    provider: 'google',
  },
];
